env:
  global:
  - CODECOV_TOKEN="5444f3fc-9598-470f-b836-e91611ce528b"

# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

jdk:
- openjdk11
- openjdk-ea

matrix:
  allow_failures:
  - jdk: openjdk-ea

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - masyam@mail.ru
    on_success: never # default: change
    on_failure: always # default: always